name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy-ui:
    name: Deploy UI
    runs-on: ubuntu-latest
    defaults:
      run:
        # only applies to `run`
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          cache-dependency-path: ui/yarn.lock
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          single-commit: true
          branch: gh-pages
          folder: ./ui/dist
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            api/target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('api/**/Cargo.lock') }}
      - name: Get Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
      - run: cargo test
        working-directory: ./api
      - name: Deploy to Heroku
        working-directory: ./api
        run: |
          git init
          git add .
          git commit -am "deploy"
          git push --force https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git master
          rm -rf .git
