name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy-ui:
    name: Deploy UI
    runs-on: ubuntu-latest
    defaults:
      run:
        # only applies to `run`
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          cache-dependency-path: ui/yarn.lock
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          single-commit: true
          branch: gh-pages
          folder: ./ui/dist
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Rust dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
      # - run: cargo test
      #   working-directory: ./api
      - run: git branch
      - name: Deploy to Heroku
        run: |
          git checkout main
          git subtree split --prefix api -b heroku-build
          git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git heroku-build:master
          git branch -D heroku-build
