name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          cache-dependency-path: ui/yarn.lock
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          single-commit: true
          branch: gh-pages
          folder: ./build
